export const ADD_TRENDS_SEARCH = "ADD_MAIN_TRENDS_SEARCH";
export const DELETE_TRENDS_SEARCH = "DELETE_MAIN_TRENDS_SEARCH";
export const RESET_TRENDS_SEARCH = "RESET_MAIN_TRENDS_SEARCH";
export const INIT_TRENDS_SEARCH = "INIT_MAIN_TRENDS_SEARCH";
export const ADD_CREATED_TRENDS_SEARCH = "ADD_CREATED_TRENDS_SEARCH";