export const ADD_TRENDS_BOOKMARKS = "ADD_MAIN_TRENDS_BOOKMARKS";
export const DELETE_TRENDS_BOOKMARKS = "DELETE_MAIN_TRENDS_BOOKMARKS";
export const RESET_TRENDS_BOOKMARKS = "RESET_MAIN_TRENDS_BOOKMARKS";
export const INIT_TRENDS_BOOKMARKS = "INIT_MAIN_TRENDS_BOOKMARKS";
export const ADD_CREATED_TRENDS_BOOKMARKS = "ADD_CREATED_TRENDS_BOOKMARKS";