export const ADD_TRENDS_SHARES = "ADD_MAIN_TRENDS_SHARES";
export const DELETE_TRENDS_SHARES = "DELETE_MAIN_TRENDS_SHARES";
export const RESET_TRENDS_SHARES = "RESET_MAIN_TRENDS_SHARES";
export const INIT_TRENDS_SHARES = "INIT_MAIN_TRENDS_SHARES";
export const ADD_CREATED_TRENDS_SHARES = "ADD_CREATED_TRENDS_SHARES";