type trendsCategoriesI = {
    number: number;
    name: string;
}

const categories: trendsCategoriesI[] = [
    { number: 0, name: 'News' },
    { number: 1, name: 'Technology' },
    { number: 2, name: 'Science' },
    { number: 3, name: 'Politics' },
    { number: 4, name: 'Sports' },
    { number: 5, name: 'Health' },
    { number: 6, name: 'Fashion' },
    { number: 7, name: 'Cooking' },
    { number: 8, name: 'Music' },
    { number: 9, name: 'Movies' },
    { number: 10, name: 'Books' },
    { number: 11, name: 'Travel' },
    { number: 12, name: 'Photography' },
    { number: 13, name: 'Art' },
    { number: 14, name: 'History' },
    { number: 15, name: 'Education' },
    { number: 16, name: 'Environment' },
    { number: 17, name: 'Animals' },
    { number: 18, name: 'Science Fiction' },
    { number: 19, name: 'Humor' },
    { number: 20, name: 'Philosophy' },
    { number: 21, name: 'Psychology' },
    { number: 22, name: 'Parenting' },
    { number: 23, name: 'Automobiles' },
    { number: 24, name: 'Entertainment' },
    { number: 25, name: 'Economy' },
    { number: 26, name: 'Business' },
    { number: 27, name: 'Video Games' },
    { number: 28, name: 'Spirituality' },
    { number: 29, name: 'Interior Design' },
    { number: 30, name: 'Fitness' },
    { number: 31, name: 'Nutrition' },
    { number: 32, name: 'Marketing' },
    { number: 33, name: 'Humanities' },
    { number: 34, name: 'Pop Culture' },
    { number: 35, name: 'Ethical Fashion' },
    { number: 36, name: 'Biographies' },
    { number: 37, name: 'Astronomy' },
    { number: 38, name: 'Alternative Medicine' },
    { number: 39, name: 'Creative Hobbies' },
    { number: 40, name: 'Urban Ecology' },
    { number: 41, name: 'Comics' },
    { number: 42, name: 'Archaeology' },
    { number: 43, name: 'Podcasts' },
    { number: 44, name: 'Hiking' },
    { number: 45, name: 'Adventure' },
    { number: 46, name: 'Entrepreneurship' },
    { number: 47, name: 'Horseback Riding' },
    { number: 48, name: 'Investment' },
    { number: 49, name: 'Geopolitics' },
    { number: 50, name: 'Nudity' }
]

export default categories;