export const ADD_TRENDS = "ADD_PROFILE_TRENDS";
export const DELETE_TRENDS = "DELETE_PROFILE_TRENDS";
export const RESET_TRENDS = "RESET_PROFILE_TRENDS";
export const INIT_TRENDS = "INIT_PROFILE_TRENDS";