export const ADD_TRENDS = "ADD_TOP_WORLD_TRENDS";
export const DELETE_TRENDS = "DELETE_TOP_WORLD_TRENDS";
export const RESET_TRENDS = "RESET_TOP_WORLD_TRENDS";
export const INIT_TRENDS = "INIT_TOP_WORLD_TRENDS";