export const ADD_TRENDS = "ADD_COMMENT_TRENDS";
export const DELETE_TRENDS = "DELETE_COMMENT_TRENDS";
export const RESET_TRENDS = "RESET_COMMENT_TRENDS";
export const INIT_TRENDS = "INIT_COMMENT_TRENDS";