export const ADD_NOTIFICATION_FEED = "ADD_NOTIFICATION_FEED";
export const RESET_NOTIFICATION_FEED = "RESET_NOTIFICATION_FEED";
export const INIT_NOTIFICATION_FEED = "INIT_NOTIFICATION_FEED";
export const MARK_READ_NOTIFICATION_FEED = "MARK_READ_NOTIFICATION_FEED";
export const MARK_READ_ONE_NOTIFICATION_FEED = "MARK_READ_ONE_NOTIFICATION_FEED";