export const ADD_TRENDS = "ADD_MAIN_TRENDS";
export const DELETE_TRENDS = "DELETE_MAIN_TRENDS";
export const RESET_TRENDS = "RESET_MAIN_TRENDS";
export const INIT_TRENDS = "INIT_MAIN_TRENDS";
export const ADD_CREATED_TRENDS = "ADD_CREATED_TRENDS";